Update on response
pagopa/io-react-native-zendesk pull request #17
Opened 2022-02-07 17:55 UTC by debiff

This PR adds the interface that allows getting the number of unread messages.

Note that before calling `hasNewResponse` method initialization is needed. Every time you perform the initialization steps the result is refreshed, otherwise, the result is refreshed every hour.

In the video you can see the response of the method and the 2 unread messages.

https://user-images.githubusercontent.com/11773070/152843997-40e8b3be-368f-4190-b913-0b791b7b12de.mov

## How to test
I suggest the following steps:
- add the method in `ts/utils/supportAssistance.ts`
- in `ts/features/zendesk/saga/networking/handleHasOpenedTickets.ts` substitute the `hasOpenedTickets` call with the `hasNewResponse`
- Press the ask assistance button "`?`"
- Check the result

2022-02-07 18:59 UTC, Undermaken requested changes

2022-02-07 18:59 UTC, Undermaken commented on index.d.ts
> +  export function hasNewResponse(): Promise<number>;
```suggestion
  export function hasNewResponses(): Promise<number>;
```
Using the singular the name could suggest true/false value

2022-02-08 08:52 UTC, debiff commented on index.d.ts
> +  export function hasNewResponse(): Promise<number>;
You're right, thank you! Modified in [8de728a](https://github.com/pagopa/io-react-native-zendesk/pull/17/commits/8de728a3b28f23ddead68d2ec43e5275797d6b32)

2022-02-08 10:21 UTC, Undermaken approved these changes

2022-02-08 10:21 UTC, merged